export enum UserRole {
  ADMIN = 'ADMIN',
  ADVERTISER = 'ADVERTISER',
  INSPECTOR = 'INSPECTOR',
  FINANCE = 'FINANCE'
}

export enum AdSlotType {
  BILLBOARD = 'BILLBOARD',
  BUS_STOP = 'BUS_STOP',
  SUBWAY = 'SUBWAY',
  STREET_LAMP = 'STREET_LAMP',
  BUILDING = 'BUILDING',
  LED_SCREEN = 'LED_SCREEN'
}

export enum AdSlotStatus {
  ACTIVE = 'ACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  DECOMMISSIONED = 'DECOMMISSIONED'
}

export enum ApplicationStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING_DESIGN = 'PENDING_DESIGN',
  DESIGN_APPROVED = 'DESIGN_APPROVED',
  DESIGN_REJECTED = 'DESIGN_REJECTED',
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  ACCEPTED = 'ACCEPTED',
  ACCEPTANCE_REJECTED = 'ACCEPTANCE_REJECTED',
  PUBLISHED = 'PUBLISHED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum WorkOrderType {
  MAINTENANCE = 'MAINTENANCE',
  RECTIFICATION = 'RECTIFICATION',
  DEMOLITION = 'DEMOLITION',
  RENEWAL_REMINDER = 'RENEWAL_REMINDER'
}

export enum WorkOrderStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum InspectionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum BillStatus {
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE'
}

export enum NotificationType {
  APPLICATION_STATUS = 'APPLICATION_STATUS',
  WORK_ORDER = 'WORK_ORDER',
  INSPECTION = 'INSPECTION',
  BILL = 'BILL',
  EXPIRATION_REMINDER = 'EXPIRATION_REMINDER'
}
